language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install runscript
  - pip install coverage
  - pip install coveralls
  - pip install flake8
  - python setup.py develop
script:
  - coverage run --source=selection -m runscript.cli test
after_success:
  coveralls
